### ISSUE TITLE
Class name change to ServiceWorkerGlobalScopeMock?

### ISSUE THREAD

**Issue by 13rac1** [pinterest/service-workers#110]
The `service-worker-mock` class `ServiceWorkerGlobalScope`, implements the [ServiceWorkerGlobalScope](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope) interface, but adds a few new properties and methods like `trigger()`. 

https://github.com/pinterest/service-workers/blob/1940ec4c2ad360ab0abfc4e133e10355bf584e58/packages/service-worker-mock/index.js#L43

Can it be changed to `ServiceWorkerGlobalScopeMock`? *Yes, A breaking change request.* I'm working on writing a TypeScript declaration file for this project, but `ServiceWorkerGlobalScope` is already use by the [interface](https://github.com/Microsoft/TypeScript/blob/40bd7c89abbdf79493e2ea20dd80d9eb657dc82e/lib/lib.webworker.d.ts#L2577) and [class](https://github.com/Microsoft/TypeScript/blob/40bd7c89abbdf79493e2ea20dd80d9eb657dc82e/lib/lib.webworker.d.ts#L2597) in the TypeScript libraries. Partial example of what could exist: `@types/service-worker-mock/index.d.ts`
```typescript
declare module 'service-worker-mock' {
  interface IEnvOptions {
    [key: string]: string;
  }

  interface IListeners {
    [key: string]: (<K extends keyof ServiceWorkerGlobalScopeEventMap>(this: ServiceWorkerGlobalScope, ev: K) => any);
  }

  function makeServiceWorkerEnv(envOptions?: IEnvOptions): ServiceWorkerGlobalScopeMock;
  export default makeServiceWorkerEnv;

  export class ServiceWorkerGlobalScopeMock extends ServiceWorkerGlobalScope {
    public listeners: IListeners;
    constructor(envOptions?: IEnvOptions);

    public trigger(name: string, args: Request): Promise<Response>;
    public trigger(name: string, args: any): Promise<void>;
  }
}
```

The workaround is [global augmentation](https://github.com/Microsoft/TypeScript-Handbook/blob/fa9e2be1024014fe923d44b1b69d315e8347e444/pages/Declaration%20Merging.md#global-augmentation), but that's not ideal for a number of reasons. Example `global.ts`:
```typescript
declare global {
  interface ServiceWorkerListener {
    [key: string]: (<K extends keyof ServiceWorkerGlobalScopeEventMap>(this: ServiceWorkerGlobalScope, ev: K) => any);
  }
  interface ServiceWorkerGlobalScope {
    listeners: ServiceWorkerListener;

    trigger(name: string, args: Request): Promise<Response>;
    trigger(name: string, args: any): Promise<void>;
  }
}
```

Or perhaps someone has another better workaround?

**Comment by kommander** [comment]
Hi, that would be breaking if someone uses the class name of `global.ServiceWorkerGlobalScope` to compare for whatever reason. Otherwise if you would use `instanceof` and you are in the mocked env everything would still work. Curious if that would break anyones tests. I like the idea of having TypeScript definitions for the mock interface.

Another approach could be to implement the existing `ServiceWorkerGlobalScope` as a mock, expose only this interface on `global.ServiceWorkerGlobalScope` and export mock helper methods with the parent class from `makeServiceWorkerEnv` to be assigned to global.

```js
// Pseudo code
// Mock ServiceWorkerGlobalScope implementation
class ServiceWorkerGlobalScope() {
  constructor() {
    throw new TypeError('Illegal constructor')
  }

  // ...mock other interface methods with noops as they cannot be used anyway...
}

class ServiceWorkerGlobalScopeMock extends ServiceWorkerGlobalScope {
  constructor(options){
    // same Implementation as now
    // ...
    this.ServiceWorkerGlobalScope = ServiceWorkerGlobalScope
    // ... 
    // Expose helper methods (on a single property interface maybe)
    this.mock = createMockHelperMethods(this, options)
  }
}

export makeEnv(options) {
  return new ServiceWorkerMockEnv(options)
}
```

**Comment by kommander** [comment]
Just come to think of it... that would affect other types as well like `Blob`, `Body`, `Request/Response` etc. which all differ from the types in the spec to provide a mock.

**Comment by zackargyle** [comment]
Hey! I'm definitely open to figuring something out, but a breaking change just to update types is probably a bit overkill, especially since this is for a testing helper. I am definitely not a Typescript expert so I'm probably not the best one to help with a solution.

**Comment by 13rac1** [comment]
> that would be breaking if someone uses the class name of global.ServiceWorkerGlobalScope to compare for whatever reason.

Yes, but that actually doesn't need to change. Only these two lines (plus tests) would change:

https://github.com/pinterest/service-workers/blob/1940ec4c2ad360ab0abfc4e133e10355bf584e58/packages/service-worker-mock/index.js#L43
https://github.com/pinterest/service-workers/blob/1940ec4c2ad360ab0abfc4e133e10355bf584e58/packages/service-worker-mock/index.js#L111

> Another approach could be to implement the existing ServiceWorkerGlobalScope as a mock,

It's already implemented to the spec with `tsc --lib webworker` (with hassles) or [`types-serviceworker`](https://www.npmjs.com/package/types-serviceworker) (without hassles.) I have a 100% TypeScript project done now, but using global augmentation and previously with a private fork of `service-workers-mock` with those two lines changed.

> a breaking change just to update types is probably a bit overkill, especially since this is for a testing helper.

I agree it's difficult, but it is a valid reason for a v2. Though, I hope there is another solution other than global augmentation, since it must be imported in for every test file.

**Comment by 13rac1** [comment]
I've finally been able to publish the project. _Super_ basic types for this project are added in https://github.com/udacity/cloudflare-typescript-workers/blob/master/packages/%40udacity/types-service-worker-mock/src/global.ts Not in the global NPM namespace because it is totally incomplete. This works, it's just non-ideal.

I'm closing the issue for now. Please consider a Class name change in the next major version.
