### ISSUE TITLE
[service-worker-mock] Unable to trigger the "activate" event.

### ISSUE THREAD

**Issue by SashaKoro** [pinterest/service-workers#113]
Hello. I am trying to use the service-worker-mock library and I seem to be failing right from the get-go. I'm unable to trigger the "activate" listener by using the `self.trigger('activate');` method. 

I created a test repo that reproduces my issue: https://github.com/SashaKoro/service-worker-mock-test-repo. I am using the shortened version of the "Use" code example as my test case: https://github.com/pinterest/service-workers/blob/master/packages/service-worker-mock/README.md#use

The behavior I am expecting is that the "activate" event is triggered and my console.log statement ('I am activated') is logged. The behavior I'm seeing is that the "activate" event is not triggered. 

When I debug the code I get to this point inside of `service-worker-mock/index.js`: 

![image](https://user-images.githubusercontent.com/22783686/55004351-78246400-4fb0-11e9-98bd-657e18d09afd.png)

The "listeners" Map object does not have an element with the "activate" key on it.

**Comment by david-ogalego** [comment]
It seems that the Object.assign is not copying the EventTarget functions, as they are in the prototype and they are not enumerable properties.

This is how I monkey-patched myself, until the library updates:

```js const events = ['addEventListener', 'dispatchEvent', 'resetEventListeners'];
const swEnv = makeServiceWorkerEnv();
Object.assign(global, swEnv);
events.forEach(element => {
    global[element] = swEnv[element];
});

**Comment by zackargyle** [comment]
I cloned your repo and it printed out as expected. Not sure what your issue is. I did, however, wipe out the yarn lockfile before installing because there was a weird npm target (npm.kroger.com). Maybe try that.

![Screen Shot 2019-04-10 at 11 23 00 AM](https://user-images.githubusercontent.com/3934294/55903649-04bf4c80-5b83-11e9-8944-efbf15d502dc.png)
