### ISSUE TITLE
[Feature Request] Support ES5 environments

### ISSUE THREAD

**Issue by mikefowler** [pinterest/service-workers#27]
Hi! We'd love to give this a spin, especially the mocking functionality, but are currently unable to because the project only ships ES6 code, and our test environment is running Node 4.

**Comment by zackargyle** [comment]
Hey @mikefowler! Do you know which js features it was choking on? In general I tried to make it stick only to the base es2015 feature set. At Pinterest we are on Node 4.4.x and haven't had issues.

**Comment by mikefowler** [comment]
Hi @zackargyle! The issue I'm running into is `SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode` being thrown at the point that I import `service-worker-mock` into a Jest spec. It's choking on the `const` declarations in `index.js` of this package.

**Comment by zackargyle** [comment]
Oh interesting. Can we just add `"use-strict";` to the top of all the files? If that works, it'd be an easy opportunity to contribute to the project!

**Comment by ljharb** [comment]
`"use strict"` (no hyphen) would make it work in node 4, but not in node < 4. Is there any reason not to babel-transpile prepublish?

**Comment by zackargyle** [comment]
The reason not to was because we didn't need to. If more people want to use the project but can't because of node version requirements, I'm happy to add the transpilation.

Looks like ~70% of Node projects use 4 or above ([Node Survey Report](https://nodejs.org/static/documents/2016-survey-report.pdf). So maybe it is worth transpiling on prepublish for the potential other 30%.

**Comment by ljharb** [comment]
Code that uses Service Workers might also run in *browsers* which don't support service workers (even though, obviously, it wouldn't be expected to work) - but it *would* be expected to parse, which `const` wouldn't do.

**Comment by mikefowler** [comment]
@zackargyle, as it turns out, we're updating to Node 6 _tonight_ (🎉), so this likely won't be an issue for us anymore. As you pointed out, though, shipping transpiled would allow more teams to give these libraries a shot.

**Comment by zackargyle** [comment]
@mikefowler Any update/issues/requests/problems? Curious if you ended up using any of the tools, and if not, what you went with. Thanks!
