### ISSUE TITLE
Expose Cache Prototype on global?

### ISSUE THREAD

**Issue by gauntface** [pinterest/service-workers#34]
I was just looking into mocking Cache prototype to check library code was putting the expected values, but I couldn't find a good way to do it beyond faking `caches.open` and then stubbing the cache at this point.

Normally I would stub / spy on a Classes prototype on the global environment.

**Comment by zackargyle** [comment]
Everything should be available globally, so it should be doable to spy/stub whatever you'd like. Does the "snapshot" not have the information you're interested in? You should be able to do self.caches.snapshot() or self.snapshot().caches. It should return a key/value dict of cached responses.

(I'm OOO right now so I'll try to be responsive but might be delayed!)

**Comment by gauntface** [comment]
I wanted to actually stub the `Cache` prototype (I *think* I wanted to spy on all puts and matches).

Essentially I would like to just add Cache to the environment same as Request and Response (See line after ...):

```javascript
const env = {
    listeners: {},
    location: { origin: '/' },
    skipWaiting: () => Promise.resolve(),
    caches: new CacheStorage(),
    clients: new Clients(),
    registration: new ServiceWorkerRegistration(),
    ....
    Cache: Cache,
    Request: Request,
    Response: Response,
    URL: url.URL || url.parse
  };
```

No rush on responses (I'm on and off of Github tracking)

**Comment by zackargyle** [comment]
I'm happy to add this in if we need to. If all you're doing is verifying that `"library code was putting the expected values"`, you shouldn't need to spy on anything, but instead can inspect the contents of the cache directly.

```js
const prevItemsInCache = self.caches.snapshot()[cacheKey];
expect(prevItemsInCache[requestUrl]).toBeUndefined();
await workbox.doThingThatInsertsAthing(thing);
const itemsInCache = self.caches.snapshot()[cacheKey];
expect(itemsInCache[requestUrl]).toBeDefined();
```
