### ISSUE TITLE
Response status 0 (opaque response) isn't supported

### ISSUE THREAD

**Issue by gauntface** [pinterest/service-workers#35]
if you try and initialise the Response with a status 0, the line (init && init.status) will equate to false, falling back to 200.

Happy to PR a fix, would just be checking if status is a number and using it other wise falling back to 200.

**Comment by zackargyle** [comment]
Ah yes. Good catch. Would love to accept a PR! I won't have my computer until Friday, so if you can wait until then I'm happy to merge. Won't be able to push a new version til then.

**Comment by gauntface** [comment]
No rush. Will put together something tomorrow.

**Comment by zackargyle** [comment]
Published in version `1.2.3`
