### ISSUE TITLE
Add ServiceWorkerGlobalScope and make self an instance of ServiceWorkerGlobalScope

### ISSUE THREAD

**Issue by gauntface** [pinterest/service-workers#43]
This may be a bit edge case-y for this mock library but thought I'd raise in case there was an appetite for it ;)

In Workbox we're adding some checks to make sure that developers only try to use the modules in a service worker env. The way to test for this is to check for `ServiceWorkerGlobalScope` and make sure self is in an instance of `ServiceWorkerGlobalScope`.

Mock could just create a class and assign it to `global.ServiceWorkerGlobalScope` and then make self an instance of that class.

**Comment by zackargyle** [comment]
I think this makes a lot of sense. Created #44 to address the request. Let me know if that will work for you!

**Comment by zackargyle** [comment]
This has been published to `@1.3.0`.
