### ISSUE TITLE
skipWaiting() and clientsClaim()

### ISSUE THREAD

**Issue by gauntface** [pinterest/service-workers#46]
This two methods could just return promises.

Happy to PR in if you're ok with adding them.

**Comment by zackargyle** [comment]
`self.skipWaiting` should already return a promise. And I can't find any documentation about `self.clientsClaim()`, are you referring to `self.clients.claim()`? That should be supported.

**Comment by gauntface** [comment]
sorry - yea that's what I'm referring to. I probably messed up naming and looked in the wrong place.
