### ISSUE TITLE
The Headers API is missing methods

### ISSUE THREAD

**Issue by philipwalton** [pinterest/service-workers#48]
Looks like `get` is the only method mocked:
https://github.com/pinterest/service-workers/blob/master/packages/service-worker-mock/models/Headers.js

I may be able to submit a PR in a few days, but if someone else can get to it sooner, that'd be much appreciated :)

**Comment by zackargyle** [comment]
Yes, this mock definitely needs some love!

**Comment by zackargyle** [comment]
This should be fixed now!
