### ISSUE TITLE
dom-urls doesn't support URLSearchParams

### ISSUE THREAD

**Issue by jeffposnick** [pinterest/service-workers#68]
As of https://github.com/pinterest/service-workers/pull/55/files#diff-e1168ac13d5f5e7fbe5bbfec6e1af547L1 (released in v1.6.0), `dom-urls` is used unconditionally in the service worker mock environment, instead of the native `url` module.

This leads to a better experience in `node` 6 and below, but for `node` 7 and 8, the first-party `url` module's `URL` object is more robust than `dom-urls`. The first-party module exposes `searchParams`, and `dom-urls` does not.

We bumped into this issue when moving from `1.5.0` to `1.7.0 of `service-worker-mock` in our Workbox tests: https://ci.appveyor.com/project/philipwalton/workbox/build/1.0.76#L713

I'm going to file a PR to prefer the first-party module when the new WHATWG `URL` object is exposed, and fall back to `dom-urls` when it's not. (It means our Workbox tests will fail on `node` 6 and below, but our CI environment uses `node` 8, so I think we can live with that.)

**Comment by zackargyle** [comment]
Thanks for the PR!
