### ISSUE TITLE
cacheStorage.match accepts options

### ISSUE THREAD

**Issue by gauntface** [pinterest/service-workers#71]
The cacheStorage.match function here: https://github.com/pinterest/service-workers/blob/master/packages/service-worker-mock/models/CacheStorage.js#L9 should accept some options, including a `cacheName` value which should restrict the search of caches to a specific cache.

For more info: https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage/match

**Comment by kommander** [comment]
It accepts `options.cacheName` with this PR https://github.com/pinterest/service-workers/pull/109
