### ISSUE TITLE
Add fetch mock to service-worker-mock

### ISSUE THREAD

**Issue by kontrollanten** [pinterest/service-workers#77]
Thanks for a great mocking tool!

Is there any reason why you don't provide a simple mock/swallow function for `fetch`? I was on my way giving up this package (thanks God I didn't) cause I couldn't find how I was supposed to handle the lack of `fetch` function. Maybe it's just that I'm rarely stupid. Either way I think it would be great if everything worked out of the box.

**Comment by zackargyle** [comment]
Hey! Thanks for the question and it is definitely something that I went back-and-forth on when creating the package. Essentially it boiled down to a separation of what belonged to a service-worker and what belonged to the classical `window` object. Fetch was not SW specific so I decided to leave it out. That's actually a great point though that we should call it out specifically in the README, maybe a suggestion of how to mock it out as well. Maybe something like this?

> If you are not using jsdom or another node DOM implementation, you will likely need to mock the global `fetch` function yourself. The mocked function should return a promise. A simple example would be:
  ```js
    global.fetch = (url) => Promise.resolve({ result: 12345 });
  ```

**Comment by kontrollanten** [comment]
I see! That looks good!

Eventually, even though it's not a part of SW, it could be provided by the module just as a convinient way for the users to mock it. But then clearly separated, something like:

```
const makeServiceWorkerEnv = require('service-worker-mock');
const mockFetch = require('service-worker-mock/fetch');

describe('Service worker', () => {
  beforeEach(() => {
    Object.assign(
      global,
      makeServiceWorkerEnv(),
      mockFetch(),
    );
    jest.resetModules();
  });

  ...
});
```

But I'm not sure if it really make sense. Your proposal is anyway a step forward and will make it easier to get up and running.

**Comment by zackargyle** [comment]
I'd be okay adding a fetch mock in that fashion as well. If you'd like to contribute I'd be more than happy to review either a documentation update or the addition of the mock under `/service-worker-mock/fetch`
