### ISSUE TITLE
TravisCI failing

### ISSUE THREAD

**Issue by onemanclapping** [pinterest/service-workers#84]
Hey folks,

We just recently opened a PR #83 which build failed on Travis. Would you please take a look at this?

Thanks.

Travis output:

```
$ ruby --version
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
$ rvm --version
rvm 1.29.3 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
$ bundle --version
Bundler version 1.16.1
$ gem --version
2.7.6
0.28s$ rake
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
```

**Comment by zackargyle** [comment]
Hey! Sorry I was out of office last week. Can you reopen the pull request so I can see the travis output? Happy to debug.

**Comment by DomingosMartins** [comment]
Hi @zackargyle i've open the pull request again.

Tanks.
